#ifndef _LOGINSERVERPROTOCOL_H_
#define _LOGINSERVERPROTOCOL_H_

enum class PACKET_TYPE
{
	PACKET_TYPE_HEAD = 0x100000,
	LOGIN_SERVER,
	DATABASE_SERVER,
};

enum class LOGIN_PACKET_TYPE
{
	LOGIN_PACKET_TYPE_HEADER = 0xfedc,
	PROCESS_START,
	LOGIN_REQUEST,
	REGISTER_REQUEST,
	JOIN_REQUEST,
	REQUEST_RESULT,
	CORE_CONNECTION
};

enum class LOGIN_ERROR_TYPE
{
	LOGIN_SUCCESS,
	JOIN_SUCCESS,
	ID_EXIST,
	NICK_EXIST
};

#endif // !_LOGINSERVERPROTOCOL_H_
