#ifndef _PROTOCOL_H_
#define _PROTOCOL_H_

#define		BUFFER_SIZE		4096
#define		MAX_CONNECTION	25000
#define		MAX_ROOM		15000
//enum class PACKET_TYPE
//{
//	/*Head of PACKET_TYPE*/
//	PACKET_TYPE_HEAD = 0x100000,
//
//	PROCESS_START,
//
//	/*
//	ENUM	:	HEADER
//	CHAR	:	USER_ID[30]
//	CHAR	:	USER_PASSWD[12]
//	*/
//	LOGIN_REQUEST,			///로그인 요청
//
//							/*
//							ENUM	:	HEADER
//							CHAR	:	USER_ID[30]
//							CHAR	:	USER_PASSWD[12]
//							CHAR	:	USER_NICK[30]
//							*/
//	JOIN_REQUEST,			///가입 요청
//
//							/*
//							ENUM	:	HEADER
//							ENUM	:	CHESS_PIECE_TYPE
//							INT		:	MOVING_POS[GRID NUM]
//							*/
//	PIECE_MOVING,			///말의 움직임
//
//	PIECE_MOVING_REQUEST,
//	/*
//	ENUM	:	HEADER
//	CHAR	:	MESSAGE[512]
//	*/
//	MESSAGE_BROADCAST,		///채팅
//
//							/*
//							ENUM	:	HEADER
//							ENUM	:	ERROR_TYPE
//							*/
//	REQEUST_RESULT,
//
//	QUICKJOIN_REQUEST,
//
//	ROOM_LIST_REQUEST,
//
//	ROOM_JOIN_REQUEST,
//
//	ROOM_LEAVE_REQUEST,
//
//	ROOM_CREATE_REQUEST,
//
//	READY_REQUEST,
//
//	START_REQUEST,
//
//	START_REQUEST_FIRST,
//
//	OPPONENT_DISCONNECTED,
//
//	GAME_WIN,
//
//	GAME_LOSE,
//
//	STATUS_CHECK
//
//};

enum class TEAM_TYPE { NONE, ENEMY, ALLY };

enum class PIECE_TYPE
{
	PIECE_TYPE_HEAD = 0x10101,
	NONE, PAWN1, PAWN2, PAWN3, PAWN4, PAWN5, PAWN6, PAWN7, PAWN8,
	L_ROOK, L_KNIGHT, L_BISHOP, KING, QUEEN, R_BISHOP, R_KNIGHT, R_ROOK
};

enum class ERROR_TYPE
{
	ERROR_TYPE_HEAD = 0x13579,

	QUICK_JOIN_FAIL,
	QUICK_JOIN_SUCCESS,

	PIECE_MOVING_SUCCESS,
	INTEGRITY_FAIL,

	LOGIN_FAILED,
	LOGIN_SUCCESS,

	JOIN_ALREADY_ID_EXIST,
	JOIN_ALREADY_NICK_EXIST,
	JOIN_SUCCESS,
	JOIN_FAILED,

	ROOM_CREATE_SUCCESS,
	ROOM_CREATE_FAIL,

	ROOM_JOIN_SUCCESS,
	ROOM_JOIN_FAILED,

	MESSAGE_SEND_SUCCESS,
	MESSAGE_SEND_FAIL,

	INQUIRY_ROOM_FAILED,

	SUCCESS_TO_CHNAGE_READY_STATE,
	SUCCESS_TO_START,

	SUCCESS_TO_LEAVE_ROOM,

	REQUEST_OK,
};

enum class QUERY_TYPE
{
	QUERY_TYPE_HEADER,
	CHECK_ID,
	CHECK_NICK,
	LOGIN_REQUEST,
	REGISTER_CHECK,
	JOIN_REQUEST,
	RANK_REQUEST,
};

#endif // !_PROTOCOL_H_
